### ISSUE TITLE
Sharp escaping or using a character other than sharp

### ISSUE THREAD

**Issue by alexarchambault** [sbt/sbt-boilerplate#12]
When generating a template with type-lambdas (like in `({ type Out[A] = ... })#Out`), one runs into errors because of the sharp character in the type-lambda.

There seems to be no way of escaping it. As a quick fix for a unpublished yet project of mine, I made some changes in sbt-boilerplate so that users can use another character instead of `#`, by adding to their build.sbt a line of the form:

    Boilerplate.boilerplateSpecialToken in Boilerplate.boilerplateGenerate := "$"

to use `$` instead of `#` for example. These changes are in my fork (https://github.com/alexarchambault/sbt-boilerplate) for now.

So my question is: do you intend to allow escaping of the sharp character at some point? Or could my fix be of any interest to you?

**Comment by ryan-richt** [comment]
Same issue with using Scala's type projections (T#X). Would love to see this merged into a new published version!

**Comment by marklister** [comment]
@ryan-richt, one workaround is to package a source dependency on a fork:  see https://github.com/marklister/product-collections/blob/master/project/project/build.scala

The hashcode makes the dependency stable.

**Comment by jrudolph** [comment]
I finally merged @marklister's fix and will soon make a release. Sorry for the hold-up.
