### ISSUE TITLE
Add a .scala extension to generates files

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt-boilerplate#18]
Generated files currently don't have an extension, which seems to confuse IntelliJ when it tries to locate sources. Is there a particular reason for the lack of extension, other than it's not strictly required by SBT?

**Comment by jrudolph** [comment]
The idea is to name the templates like this: "abc.scala.template". For example, see https://github.com/akka/akka/tree/master/akka-stream/src/main/boilerplate/akka/stream/scaladsl.

On the other hand, you will most likely generate only scala files, so I agree it makes sense to append ".scala" if the file-name without ".template" doesn't have an extension.

**Comment by nrinaudo** [comment]
Oh yes, that makes a lot of sense, I didn't even think about doing it that way. I feel a bit silly now.

I'm fine with closing this as it is, but if you'd like, I can submit a PR for "append .scala if no extension is found".

**Comment by jrudolph** [comment]
Yes, I'd take that PR :)

**Comment by nrinaudo** [comment]
On it. I'll try to get something ready soon, it shouldn't be too complicated.

**Comment by jrudolph** [comment]
I've already fixed it an hour ago but didn't push the commit yet :)

**Comment by nrinaudo** [comment]
Oh. And I see you're tackling the autoplugin thing as well. I take it we're due for a release soon? :)

**Comment by jrudolph** [comment]
Yep, I hope so :)
