### ISSUE TITLE
Not all source directories searched

### ISSUE THREAD

**Issue by marklister** [sbt/sbt-boilerplate#20]
Using 0.6.0-SNAPSHOT

My project is a combined scala-js and scala-jvm project.  Here is the [build.sbt](https://github.com/marklister/product-collections/blob/master/build.sbt)

The shared/src directory is not searched for templates.

It was a while ago but I think [this hack](https://github.com/marklister/sbt-boilerplate/commit/79e0f581e7e73770162b2743b5626eb63a6bae9c) fixed this problem.

[updated build.sbt link]

**Comment by jrudolph** [comment]
Thanks for the reproduction. I sent you https://github.com/marklister/product-collections/pull/36 which seems to work for your project.

It wouldn't work if you needed several source directories. I created #21 to track this issue.

**Comment by marklister** [comment]
Appologies, I had done most of this locally except for pc.jvm.enablePlugins(spray.boilerplate.BoilerplatePlugin) and the js equivalent

**Comment by marklister** [comment]
I remember I originally had separate templates for JVM and JS because the parsers for JVM and JS were different.  I think that hack solved that problem.
