### ISSUE TITLE
Release for sbt 1.0

### ISSUE THREAD

**Issue by ktoso** [sbt/sbt-boilerplate#25]
AFAICS this was not done yet - we'll need this for Akka to be able to upgrade to 1.0.0

**Comment by jrudolph** [comment]
Yep, thanks, in fact, @eed3si9n already proposed a PR in #24. I'll try to do a release later.

**Comment by ktoso** [comment]
Ah, excellent thanks @eed3si9n :) I missed the PR

**Comment by jrudolph** [comment]
Fixed by #24. Released version 0.6.1 cross-built for sbt 1.0 and 0.13.

**Comment by ktoso** [comment]
Wohoo :)

**Comment by eed3si9n** [comment]
Nice!
